networks:
  dev-net:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "5174:5174"
    volumes:
      - ./blazor-frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    networks:
      - dev-net

  frontend:
    container_name: blazor-frontend-dev
    build:
      context: ./blazor-frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    expose:
      - "5173"
    volumes:
      - ./blazor-frontend:/app
      - /app/bin
      - /app/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_URLS=http://0.0.0.0:5173
      - DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH=1
    command: dotnet watch run --non-interactive
    depends_on:
      - api
    networks:
      - dev-net

  api:
    container_name: api-dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5159"
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mariadb;Database=baby_names_db;User=root;Password=my-secret-password;
    depends_on:
      - mariadb
    volumes:
      - ./api/baby_name_data:/app/baby_name_data
    restart: always
    networks:
      - dev-net

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: baby_names_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - dev-net
    volumes:
      - ./db/db_data_dev:/var/lib/mysql
      - ./db/my.cnf_dev:/etc/mysql/conf.d/my.cnf
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data_dev:
